apiVersion: v1
kind: Template
metadata:
  name: hawkular-openshift-agent
objects:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    labels:
      metrics-infra: agent
    name: hawkular-openshift-agent
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - namespaces
    - nodes
    - pods
    - projects
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      metrics-infra: agent
    name: hawkular-openshift-agent
- apiVersion: v1
  data:
    password: Y2hhbmdlbWU=
    username: ZGV2
  kind: Secret
  metadata:
    labels:
      metrics-infra: agent
    name: hawkular-openshift-agent-status
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      metrics-infra: agent
      name: hawkular-openshift-agent
    name: hawkular-openshift-agent
  spec:
    selector:
      matchLabels:
        name: hawkular-openshift-agent
    template:
      metadata:
        labels:
          metrics-infra: agent
          name: hawkular-openshift-agent
      spec:
        containers:
        - command:
          - /opt/hawkular/hawkular-openshift-agent
          - -config
          - /hawkular-openshift-agent-configuration/config.yaml
          - -v
          - "4"
          env:
          - name: K8S_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: EMITTER_STATUS_CREDENTIALS_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: hawkular-openshift-agent-status
          - name: EMITTER_STATUS_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: hawkular-openshift-agent-status
          image: hawkular/hawkular-openshift-agent:${IMAGE_VERSION}
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 30
          name: hawkular-openshift-agent
          volumeMounts:
          - mountPath: /master-proxy-secret
            name: master-proxy
          - mountPath: /hawkular-openshift-agent-configuration
            name: hawkular-openshift-agent-configuration
        serviceAccount: hawkular-openshift-agent
        volumes:
        - name: master-proxy
          secret:
            secretName: master-proxy
        - configMap:
            name: hawkular-openshift-agent-configuration
          name: hawkular-openshift-agent-configuration
        - configMap:
            name: hawkular-openshift-agent-configuration
          name: hawkular-openshift-agent
parameters:
- description: The version of the image to use
  name: IMAGE_VERSION
  value: dev
